import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home({ time }) {
  const timeValue = time || '123';
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>{timeValue}</h1>
      </main>
    </div>
  )
}

export async function getStaticProps() {
  const now = new Date();
  const year = now.getFullYear();
  const month = now.getMonth() + 1;
  const day = now.getDate();
  const hours = now.getHours();
  const minutes = now.getMinutes();
  const sec = now.getSeconds();

  return {
    props: {
      time: `${year}/${month}/${day} ${hours}:${minutes}:${sec}`,
    },
  };
}
